# Generated by Django 2.2.6 on 2021-02-08 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210109_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(
                help_text='Наименование группы',
                max_length=200, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(
                help_text='Наименование автора',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts', to=settings.AUTH_USER_MODEL,
                verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(
                blank=True, help_text='Выберете группу', null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='posts', to='posts.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(
                help_text='Напишите текст', verbose_name='Текст'),
        ),
    ]
